### ISSUE TITLE
Error reading file - Maven

### ISSUE THREAD

**Issue by KikyoC** [AlbeMiglio/PowerLib#13]
Hello,
I'm new with Maven.
I have this error (in title) and I absolutely don't know why.
This is my pom.xml:
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>fr.kikyo</groupId>
    <artifactId>BanGui</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>BanGui recode</name>

    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <relocations>
                                <relocation>
                                    <pattern>it.mycraft.powerlib</pattern>
                                    <shadedPattern>(your.fantastic.package).libs.powerlib</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>spigotmc-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
        <repository>
            <id>codemc-repo</id>
            <url>https://repo.codemc.org/repository/maven-public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.12-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>5.0.1</version>
        </dependency>
        <dependency>
            <groupId>it.mycraft</groupId>
            <artifactId>powerlib-<YOUR-PLATFORM></artifactId>
            <version>1.2.12</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>
`

Thank you in advance to give me a little bit from you time for me

**Comment by albemiglio** [comment]
Hi @KikyoC,
With the title I can't know anything about the issue. Please attach the entire error log.
Then, look for your powerlib relocation in shade plugin and edit `(your.fantastic.package)` with your actual package. Let me know!

**Comment by KikyoC** [comment]
Hello, I just launched Intellij and it looks like working. Thank you for you response ^^
Tom

**Comment by KikyoC** [comment]
And could you tell me where can I find the doxumentation ? Because I have a 404 error: https://github.com/AlbeMiglio/PowerLib/blob/master/Example/src/main/java/it/mycraft/powerlibexample/ExampleConfigManager.java

**Comment by albemiglio** [comment]
https://github.com/AlbeMiglio/PowerLib/wiki/Configurations#configurations-management

**Comment by KikyoC** [comment]
Oh ok sorry 😅
